services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .db.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - ./.data/database:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .wordpress.env
    secrets:
      - db_password
    volumes:
      - ./.data/wordpress:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8282:80
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt