services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - ./.data/database:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./.data/wordpress:/var/www/html

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt